name: johnny-five
version: 0.9.14
vendor: Leo Arias <elopio@ubuntu.com>
summary: The JavaScript Robotics Programming Framework
description: |
  The JavaScript Robotics and Hardware Programming Framework. Use with: Arduino
  (all models), Electric Imp, Beagle Bone, Intel Galileo & Edison, Linino One,
  Pinoccio, pcDuino3, Raspberry Pi, Particle/Spark Core & Photon, Tessel 2, TI
  Launchpad and more!
icon: assets/sgier-johnny-five.png

binaries:
  example:
    exec: node example.js

parts:
  johnny-five:
    plugin: nodejs
    source: .
  wrapper:
    plugin: copy
    files:
      example.js: example.js
